/*******************************************************************************
 * Copyright 2014-2026 Marc Lamberton
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/

package org.myphotodiary.cms.gallery;

import java.nio.charset.StandardCharsets;
import java.security.SecureRandom;
import java.time.Duration;
import java.time.Instant;
import java.util.Base64;

import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;

import org.myphotodiary.cms.config.PersistedSecrets;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

/**
 * Short-lived, signed tokens for video streaming - the auth mechanism
 * decided during the video talk (28/08/2026). A plain {@code <video src>}
 * can't carry the custom {@code Authorization} header every other endpoint
 * in this app uses (AuthImage's own comment explains why, for the same
 * reason on images) - and unlike an image, the video can't just be
 * fetch()'d as a whole blob first either, since that would defeat the whole
 * point of Range-request streaming (VideoController) for a file that can be
 * hundreds of MB. So the token travels as a query parameter instead
 * (standard practice for video/CDN streaming - S3 presigned URLs, YouTube's
 * own signed delivery URLs, etc.), validated by {@link #validateAndGetImageId}
 * rather than Spring Security's normal Basic Auth filter chain (see
 * SecurityConfig's {@code permitAll()} on the stream endpoint).
 *
 * HMAC-SHA256 over "imageId:expiryEpochSeconds", not a JWT library - this
 * project's usual bias toward the smallest thing that does the job, and a
 * token here only ever needs two claims, not a general claims framework.
 *
 * The signing key is a random value generated once per JVM start unless
 * {@code app.video.token-secret} is configured - meaning a server restart
 * invalidates any token a client is still holding (mid-playback, its next
 * seek/range request would get a 403). Accepted as a known limitation for
 * this app's personal-gallery scale: the frontend already re-requests a
 * fresh token every time a video is (re)selected (AuthVideo.jsx), so this
 * only bites an *already open* video across a restart, not a new page load.
 */
@Component
public class VideoStreamTokenService {

	private static final Duration DEFAULT_TTL = Duration.ofHours(4); // generous: long enough for one real viewing session, including pauses

	private final SecretKeySpec key;
	private final Duration ttl;

	@Autowired
	public VideoStreamTokenService(@Value("${app.video.token-secret:}") String configuredSecret, PersistedSecrets persistedSecrets) {
		this(configuredSecret == null || configuredSecret.isBlank() ? persistedSecrets.get("video-token-secret") : configuredSecret, DEFAULT_TTL);
	}

	/** Package-visible so tests can exercise expiry without waiting 4 hours or reflecting into a private constant. */
	VideoStreamTokenService(String configuredSecret, Duration ttl) {
		byte[] secretBytes;
		if (configuredSecret != null && !configuredSecret.isBlank()) {
			secretBytes = configuredSecret.getBytes(StandardCharsets.UTF_8);
		} else {
			secretBytes = new byte[32];
			new SecureRandom().nextBytes(secretBytes);
		}
		this.key = new SecretKeySpec(secretBytes, "HmacSHA256");
		this.ttl = ttl;
	}

	public String issueToken(Long imageId) {
		String payload = imageId + ":" + (Instant.now().plus(ttl).getEpochSecond());
		String signature = sign(payload);
		return encode(payload) + "." + signature;
	}

	/** @throws InvalidVideoTokenException if the token is malformed, forged, or expired. */
	public Long validateAndGetImageId(String token) {
		int dot = token.indexOf('.');
		if (dot < 0) {
			throw new InvalidVideoTokenException("Malformed video token");
		}
		String encodedPayload = token.substring(0, dot);
		String signature = token.substring(dot + 1);
		String payload;
		try {
			payload = decode(encodedPayload);
		} catch (IllegalArgumentException e) {
			throw new InvalidVideoTokenException("Malformed video token");
		}
		// Signature checked with a constant-time comparison, not `.equals()` -
		// generated by MessageDigest.isEqual, which is the JDK's standard way
		// to avoid a timing side-channel on secret comparison.
		if (!java.security.MessageDigest.isEqual(sign(payload).getBytes(StandardCharsets.UTF_8), signature.getBytes(StandardCharsets.UTF_8))) {
			throw new InvalidVideoTokenException("Invalid video token signature");
		}
		String[] parts = payload.split(":", 2);
		if (parts.length != 2) {
			throw new InvalidVideoTokenException("Malformed video token");
		}
		long expiry;
		Long imageId;
		try {
			imageId = Long.parseLong(parts[0]);
			expiry = Long.parseLong(parts[1]);
		} catch (NumberFormatException e) {
			throw new InvalidVideoTokenException("Malformed video token");
		}
		if (Instant.now().getEpochSecond() > expiry) {
			throw new InvalidVideoTokenException("Video token expired");
		}
		return imageId;
	}

	private String sign(String payload) {
		try {
			Mac mac = Mac.getInstance("HmacSHA256");
			mac.init(key);
			return encode(new String(mac.doFinal(payload.getBytes(StandardCharsets.UTF_8)), StandardCharsets.ISO_8859_1));
		} catch (java.security.GeneralSecurityException e) {
			throw new IllegalStateException("Could not sign video token", e);
		}
	}

	private static String encode(String value) {
		return Base64.getUrlEncoder().withoutPadding().encodeToString(value.getBytes(StandardCharsets.ISO_8859_1));
	}

	private static String decode(String value) {
		return new String(Base64.getUrlDecoder().decode(value), StandardCharsets.ISO_8859_1);
	}
}
