/*******************************************************************************
 * Copyright 2014-2026 Marc Lamberton
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 ******************************************************************************/

package org.myphotodiary.cms.settings;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

/**
 * The reported version must be the POM's own {@code <version>} - compared
 * against the Maven-filtered {@code build-info.properties} actually
 * generated for this build, not a hard-coded string that would need
 * updating (and could silently go stale) on every release bump.
 */
@SpringBootTest
class VersionControllerTest {

	@Autowired
	private VersionController versionController;

	@Test
	void version_isTheBuildVersion_notUnknown() throws IOException {
		Properties buildInfo = new Properties();
		try (InputStream in = getClass().getResourceAsStream("/META-INF/build-info.properties")) {
			assertThat(in).as("build-info.properties generated by spring-boot-maven-plugin").isNotNull();
			buildInfo.load(in);
		}

		String version = versionController.version().get("version");

		assertThat(version).isNotEqualTo("unknown").isEqualTo(buildInfo.getProperty("build.version"));
		assertThat(version).matches("\\d+\\.\\d+\\.\\d+.*");
	}
}
