-- Shared search results (04/10/2026, explicit ask): a search result shared
-- through an external link is *frozen* when the link is created - the exact
-- list of pictures the sharer saw, in the same order, not the criteria
-- re-run later (which would keep revealing newly added photos for 30 days).
--
-- shared_search_image references image ON DELETE CASCADE: a picture deleted
-- after the link was sent simply drops out of the shared result, at the
-- database level, whatever deleted it (the Delete button, a re-index of a
-- folder whose file is gone, an index reset). sort_order keeps the original
-- order; gaps left by deleted pictures are expected and harmless.
CREATE TABLE shared_search (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP    NOT NULL,
    expires_at  TIMESTAMP    NOT NULL,
    created_by  VARCHAR(255) NOT NULL,
    match_count INTEGER      NOT NULL
);

CREATE TABLE shared_search_image (
    shared_search_id BIGINT  NOT NULL REFERENCES shared_search (id) ON DELETE CASCADE,
    sort_order       INTEGER NOT NULL,
    image_id         BIGINT  NOT NULL REFERENCES image (id) ON DELETE CASCADE,
    PRIMARY KEY (shared_search_id, sort_order)
);

-- Most pictures one shared search result may hold (explicit ask: default
-- 50) - above it, the first 50 are shared and the sharer is warned.
ALTER TABLE app_settings ADD COLUMN max_share_size INTEGER DEFAULT 50 NOT NULL;
