-- Gallery/upload schema for the new gallery screen (myphotodiary migration,
-- ANALYSIS.md §9 point 2). Fresh schema, not a copy of the legacy one - see
-- V1's header for why (reserved-word table names, etc.).
--
-- Deliberately narrower than the legacy Directory/Image entities
-- (ANALYSIS.md §2): no latitude/longitude/indexing_allowed on directory yet
-- (map screen, ANALYSIS.md §9 point 4) and no image_attribute tagging
-- (navigation screen, §9 point 3) - both out of scope for this slice, added
-- as their own migration when that screen is built rather than speculatively
-- now. No `orientation` column either: Thumbnailator (CLAUDE.md) bakes EXIF
-- orientation into the files it writes, so - unlike the legacy Image entity -
-- there is nothing left to persist for it (ANALYSIS.md §7).
--
-- Surrogate IDENTITY keys here (unlike V1's natural keys) since directory
-- path and image name are not naturally globally unique - portable
-- SQL:2003 syntax (CLAUDE.md decision #4), runs unmodified on HSQLDB and
-- PostgreSQL 10+.

CREATE TABLE directory (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    path          VARCHAR(1000) NOT NULL UNIQUE,
    group_name    VARCHAR(255) NOT NULL,
    creation_date DATE         NOT NULL,
    FOREIGN KEY (group_name) REFERENCES app_group (group_name)
);

CREATE TABLE image (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(500) NOT NULL,
    description   VARCHAR(4000),
    rating        INTEGER      DEFAULT -1 NOT NULL,
    capture_date  TIMESTAMP,
    directory_id  BIGINT       NOT NULL,
    UNIQUE (name, directory_id),
    FOREIGN KEY (directory_id) REFERENCES directory (id) ON DELETE CASCADE
);
