-- Navigation/indexing screen schema (myphotodiary migration, ANALYSIS.md
-- §9 point 3) - directory tree, filesystem indexing, attribute tagging.
-- Adds the columns/tables deliberately left out of V2 (see its header):
-- directory-level description/attributes, latitude/longitude,
-- indexing_allowed, and image-level attributes.
--
-- Portable SQL:2003 syntax (CLAUDE.md decision #4), same as V1/V2.

ALTER TABLE directory ADD COLUMN description VARCHAR(4000);
ALTER TABLE directory ADD COLUMN latitude DOUBLE;
ALTER TABLE directory ADD COLUMN longitude DOUBLE;
-- Mirrors the legacy Directory.indexingAllowedBoolean (ANALYSIS.md §2): lets
-- a directory be excluded from automatic (re)indexing without deleting it.
ALTER TABLE directory ADD COLUMN indexing_allowed BOOLEAN DEFAULT TRUE NOT NULL;

CREATE TABLE attribute (
    id        BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(255) NOT NULL UNIQUE,
    parent_id BIGINT,
    FOREIGN KEY (parent_id) REFERENCES attribute (id)
);

CREATE TABLE directory_attribute (
    directory_id BIGINT NOT NULL,
    attribute_id BIGINT NOT NULL,
    PRIMARY KEY (directory_id, attribute_id),
    FOREIGN KEY (directory_id) REFERENCES directory (id) ON DELETE CASCADE,
    FOREIGN KEY (attribute_id) REFERENCES attribute (id) ON DELETE CASCADE
);

CREATE TABLE image_attribute (
    image_id     BIGINT NOT NULL,
    attribute_id BIGINT NOT NULL,
    PRIMARY KEY (image_id, attribute_id),
    FOREIGN KEY (image_id) REFERENCES image (id) ON DELETE CASCADE,
    FOREIGN KEY (attribute_id) REFERENCES attribute (id) ON DELETE CASCADE
);
